# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video_msg.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fvideo_msg.proto\x12\x05video\"\x80\x01\n\x0cVideoMessage\x12\x12\n\x05\x66rame\x18\x01 \x01(\x0cH\x00\x88\x01\x01\x12\x0f\n\x02id\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x12\n\x05hight\x18\x03 \x01(\x05H\x02\x88\x01\x01\x12\x12\n\x05width\x18\x04 \x01(\x05H\x03\x88\x01\x01\x42\x08\n\x06_frameB\x05\n\x03_idB\x08\n\x06_hightB\x08\n\x06_widthb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_msg_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VIDEOMESSAGE']._serialized_start=27
  _globals['_VIDEOMESSAGE']._serialized_end=155
# @@protoc_insertion_point(module_scope)
